language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install -e .[test]
  - pip install sphinx
script:
  - py.test -ra -v tests/
  - sphinx-build -b html docs/ _build/html
